# Generated by Django 3.1.1 on 2020-09-10 10:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
